---
- name: Zarządzanie klastrem Kafka
  hosts: kafka
  gather_facts: false
  vars_files:
    - ../inventory/group_vars/kafka_servers.yml
  
  tasks:
    - name: Utwórz topic w Kafka
      ansible.builtin.command:
        cmd: >
          {{ kafka_bin_path }}/kafka-topics.sh --create
          --bootstrap-server {{ kafka_bootstrap_server }}
          --topic {{ kafka_topic_name }}
          --partitions {{ kafka_partitions }}
          --replication-factor {{ kafka_replication_factor }}
          --if-not-exists
      register: kafka_topic_result
      changed_when: "'Created topic' in kafka_topic_result.stdout"

    - name: Wyświetl wynik operacji na Kafka
      ansible.builtin.debug:
        msg: "Topic '{{ kafka_topic_name }}' został pomyślnie utworzony lub już istnieje."
