---
- name: Zarządzanie klastrem Kafka
  hosts: kate163
  gather_facts: false
  vars:
    kafka_bootstrap_server: "localhost:9092"
    kafka_topic_name: "moj-nowy-topic"
    kafka_partitions: 3
    kafka_replication_factor: 1
    kafka_bin_path: "/opt/kafka/bin" # Ścieżka do skryptów CLI Kafki
